/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.produtoController;
import Model.ProdutoTableModel;
import Util.ValidaNome;
import Util.ValidaNumero;
import java.awt.Color;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lucas
 */
public class Novaview extends javax.swing.JFrame {

    ImageIcon iconNovoazul = new ImageIcon(getClass().getResource("/Imagens/icon_add_blue.png"));
    ImageIcon iconSalvarazul = new ImageIcon(getClass().getResource("/Imagens/icon_save_blue.png"));
    ImageIcon iconCancelarazul = new ImageIcon(getClass().getResource("/Imagens/icon_cancel_blue.png"));
    ImageIcon iconEditarzaul = new ImageIcon(getClass().getResource("/Imagens/icon_edit_blue.png"));
    ImageIcon iconExcluirazul = new ImageIcon(getClass().getResource("/Imagens/icon_delete_blue.png"));
    
    Color cinzaClaro = new Color(188,188,188);
    
    ProdutoTableModel tableModel = new ProdutoTableModel();
    
    boolean valor = false;
    
    
    int x,y;
    /**
     * Creates new form Novaview
     */
    public Novaview() {
        initComponents();
        estadoInicialView();
        jTableView.setModel(tableModel);
        jTableView.setRowSorter(new TableRowSorter(tableModel));
        carregaDadosBanco();
        txtCodigoProduto.setDocument(new ValidaNumero());
        txtQuantidadeProduto.setDocument(new ValidaNumero());
        txtNomeProduto.setDocument(new ValidaNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtminimiza = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelControleEstoque = new javax.swing.JPanel();
        lblControleEstoque = new javax.swing.JLabel();
        jPanelEmBreve = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisarProduto = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        txtQuantidadeProduto = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblDataCompra = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        jDataCompra = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableView = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(188, 188, 188));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img_x_branco.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        txtminimiza.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtminimiza.setForeground(new java.awt.Color(255, 255, 255));
        txtminimiza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtminimiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img_linha_branca.png"))); // NOI18N
        txtminimiza.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txtminimiza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtminimiza.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        txtminimiza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtminimizaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtminimizaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtminimizaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(txtminimiza, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtminimiza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        jPanelControleEstoque.setBackground(new java.awt.Color(85, 65, 118));
        jPanelControleEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelControleEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelControleEstoqueMouseExited(evt);
            }
        });

        lblControleEstoque.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblControleEstoque.setForeground(new java.awt.Color(255, 255, 255));
        lblControleEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControleEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Database_Administrator_50px_2.png"))); // NOI18N
        lblControleEstoque.setText("ESTOQUE");

        javax.swing.GroupLayout jPanelControleEstoqueLayout = new javax.swing.GroupLayout(jPanelControleEstoque);
        jPanelControleEstoque.setLayout(jPanelControleEstoqueLayout);
        jPanelControleEstoqueLayout.setHorizontalGroup(
            jPanelControleEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblControleEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelControleEstoqueLayout.setVerticalGroup(
            jPanelControleEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblControleEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanelEmBreve.setBackground(new java.awt.Color(85, 65, 118));
        jPanelEmBreve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEmBreveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEmBreveMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_plus_write.png"))); // NOI18N
        jLabel3.setText("EM BREVE");

        javax.swing.GroupLayout jPanelEmBreveLayout = new javax.swing.GroupLayout(jPanelEmBreve);
        jPanelEmBreve.setLayout(jPanelEmBreveLayout);
        jPanelEmBreveLayout.setHorizontalGroup(
            jPanelEmBreveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jPanelEmBreveLayout.setVerticalGroup(
            jPanelEmBreveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControleEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEmBreve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanelControleEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEmBreve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 520));

        txtPesquisarProduto.setBackground(new java.awt.Color(153, 153, 153));
        txtPesquisarProduto.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtPesquisarProduto.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisarProduto.setToolTipText("Nome do produto");
        txtPesquisarProduto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPesquisarProduto.setOpaque(false);
        txtPesquisarProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisarProdutoFocusGained(evt);
            }
        });
        txtPesquisarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarProdutoMouseClicked(evt);
            }
        });
        txtPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarProdutoKeyReleased(evt);
            }
        });
        jPanel1.add(txtPesquisarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 275, 140, -1));

        txtCodigoProduto.setBackground(new java.awt.Color(153, 153, 153));
        txtCodigoProduto.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtCodigoProduto.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoProduto.setToolTipText("Nome do produto");
        txtCodigoProduto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtCodigoProduto.setOpaque(false);
        txtCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoProdutoFocusGained(evt);
            }
        });
        jPanel1.add(txtCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 180, -1));

        txtQuantidadeProduto.setBackground(new java.awt.Color(153, 153, 153));
        txtQuantidadeProduto.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtQuantidadeProduto.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantidadeProduto.setToolTipText("Nome do produto");
        txtQuantidadeProduto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtQuantidadeProduto.setOpaque(false);
        jPanel1.add(txtQuantidadeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 180, -1));

        txtNomeProduto.setBackground(new java.awt.Color(153, 153, 153));
        txtNomeProduto.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtNomeProduto.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeProduto.setToolTipText("Nome do produto");
        txtNomeProduto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNomeProduto.setOpaque(false);
        jPanel1.add(txtNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 180, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisar por nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Codigo:");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        lblNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        lblQuantidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidade.setText("Quantidade:");
        jPanel1.add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        lblDataCompra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDataCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblDataCompra.setText("Data da Compra:");
        jPanel1.add(lblDataCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        lblDescricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricao.setText("Descrição:");
        jPanel1.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jDataCompra.setBackground(new java.awt.Color(255, 255, 255));
        jDataCompra.setMaxSelectableDate(new java.util.Date(253370775699000L));
        jDataCompra.setOpaque(false);
        jPanel1.add(jDataCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 135, 140, -1));

        txtAreaDescricao.setColumns(20);
        txtAreaDescricao.setRows(3);
        jScrollPane2.setViewportView(txtAreaDescricao);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 360, 60));

        jTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableView.setFocusable(false);
        jTableView.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableViewFocusLost(evt);
            }
        });
        jTableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableViewMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableView);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 650, 230));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_save_blue.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setToolTipText("Click para salvar um item novo ou uma alteração");
        btnSalvar.setBorder(null);
        btnSalvar.setBorderPainted(false);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalvar.setIconTextGap(10);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, 30));

        btnNovo.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_add_blue.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.setToolTipText("Click para cadastrar um novo produto");
        btnNovo.setBorder(null);
        btnNovo.setBorderPainted(false);
        btnNovo.setContentAreaFilled(false);
        btnNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNovo.setIconTextGap(10);
        btnNovo.setVerifyInputWhenFocusTarget(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, 30));

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_cancel_blue.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setToolTipText("Limpa os dados na tela de cadastro");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.setIconTextGap(10);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 120, 30));

        btnEditar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_edit_blue.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setToolTipText("Selecione um item da tabela e click aqui para edita-lo");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditar.setIconTextGap(10);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, 30));

        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_delete_blue.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setToolTipText("Selecione um item da tabela e click aqui para exclui-lo");
        btnExcluir.setBorder(null);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcluir.setIconTextGap(10);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_question.png"))); // NOI18N
        jLabel4.setToolTipText("<html><h3>Ola!</h3><h4>Se estiver com alguma duvida com<br> os botoes, permanessa com o mouse sobre ele<br> que ele lhe dara uma breve explicação de como usalo!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        x = evt.getX();
        y = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        this.setLocation(this.getLocation().x+evt.getX() - x, this.getLocation().y+ evt.getY() -y);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    private void txtminimizaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtminimizaMouseExited
        ImageIcon iconLinhabranca = new ImageIcon(getClass().getResource("/Imagens/img_linha_branca.png"));
        txtminimiza.setIcon(iconLinhabranca);
    }//GEN-LAST:event_txtminimizaMouseExited

    private void txtminimizaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtminimizaMouseEntered
        ImageIcon iconLinhaVermelha = new ImageIcon(getClass().getResource("/Imagens/img_linha_vermelha.png"));
        txtminimiza.setIcon(iconLinhaVermelha);
    }//GEN-LAST:event_txtminimizaMouseEntered

    private void txtminimizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtminimizaMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_txtminimizaMouseClicked

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        ImageIcon iconXBranco = new ImageIcon(getClass().getResource("/Imagens/img_x_branco.png"));
        jLabel1.setIcon(iconXBranco);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        ImageIcon iconXVermelho = new ImageIcon(getClass().getResource("/Imagens/img_x_vermelho.png"));

        jLabel1.setIcon(iconXVermelho);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void txtCodigoProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoProdutoFocusGained
    }//GEN-LAST:event_txtCodigoProdutoFocusGained

    private void jPanelControleEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControleEstoqueMouseEntered
        jPanelControleEstoque.setBackground(new Color(151, 130, 186));                // TODO add your handling code here:
    }//GEN-LAST:event_jPanelControleEstoqueMouseEntered

    private void jPanelControleEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControleEstoqueMouseExited
        jPanelControleEstoque.setBackground(new Color(85,65,118));        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelControleEstoqueMouseExited

    private void jPanelEmBreveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmBreveMouseEntered
        jPanelEmBreve.setBackground(new Color(151, 130, 186));                // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_jPanelEmBreveMouseEntered

    private void jPanelEmBreveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmBreveMouseExited
        jPanelEmBreve.setBackground(new Color(85,65,118)); // TODO add your handling code here:
    }//GEN-LAST:event_jPanelEmBreveMouseExited

    private void txtPesquisarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoKeyReleased
        tableModel.retornoPesquisaProduto(txtPesquisarProduto.getText());
    }//GEN-LAST:event_txtPesquisarProdutoKeyReleased

    private void jTableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableViewMouseClicked
        if(jTableView.getSelectedRow() != -1){
            
            btnEditar.setEnabled(true);
            btnEditar.setForeground(Color.white);
            
            btnExcluir.setEnabled(true);
            btnExcluir.setForeground(Color.WHITE);
            
        }
        else{
            
//            btnEditar.setEnabled(false);
//            btnEditar.setForeground(cinzaClaro);
//            
//            btnExcluir.setEnabled(false);
//            btnExcluir.setForeground(cinzaClaro);
            

        }
    }//GEN-LAST:event_jTableViewMouseClicked

    private void jTableViewFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableViewFocusLost
              // TODO add your handling code here:
    }//GEN-LAST:event_jTableViewFocusLost

    private void txtPesquisarProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoFocusGained
      
    }//GEN-LAST:event_txtPesquisarProdutoFocusGained

    private void txtPesquisarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoMouseClicked
        
        btnEditar.setEnabled(false);
        btnEditar.setForeground(cinzaClaro);
        
        btnExcluir.setEnabled(false);
        btnExcluir.setForeground(cinzaClaro);
        
        jTableView.clearSelection();// TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarProdutoMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(naoCampoVazio() && validaDate()){

            SimpleDateFormat dt = new SimpleDateFormat("dd/MM/YYYY");

            produtoController novo = new produtoController();

            if(valor){
                novo.novoProduto(
                    Integer.parseInt(txtCodigoProduto.getText()),
                    txtNomeProduto.getText(),
                    Integer.parseInt(txtQuantidadeProduto.getText()),
                    String.valueOf(dt.format(jDataCompra.getDate())),
                    txtAreaDescricao.getText());

            }else{
                novo.atualizarProduto(
                    Integer.parseInt(txtCodigoProduto.getText()),
                    txtNomeProduto.getText(),
                    Integer.parseInt(txtQuantidadeProduto.getText()),
                    String.valueOf(dt.format(jDataCompra.getDate())),
                    txtAreaDescricao.getText());
            }
            limpaTela();
            carregaDadosBanco();
            estadoInicialView();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        valor = true;
        
        btnNovo.setEnabled(false);
        btnNovo.setForeground(cinzaClaro);
        
        btnEditar.setEnabled(false);
        btnEditar.setForeground(cinzaClaro);

        btnExcluir.setEnabled(false);
        btnExcluir.setForeground(cinzaClaro);
        
        btnSalvar.setEnabled(true);
        btnSalvar.setForeground(Color.white);
        
        btnCancelar.setEnabled(true);
        btnCancelar.setForeground(Color.white);
        
        
        lblCodigo.setForeground(Color.WHITE);
        txtCodigoProduto.setEnabled(true);
        
        lblNome.setForeground(Color.WHITE);
        txtNomeProduto.setEnabled(true);
        
        lblQuantidade.setForeground(Color.WHITE);
        txtQuantidadeProduto.setEnabled(true);

        lblDataCompra.setForeground(Color.WHITE);
        jDataCompra.setEnabled(true);
        
        lblDescricao.setForeground(Color.WHITE);
        txtAreaDescricao.setEnabled(true);
        
        
        jTableView.clearSelection();
        jTableView.setEnabled(false);
        
        txtCodigoProduto.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estadoInicialView();  
        limpaTela();
        jTableView.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        valor = false;
        
        btnNovo.setEnabled(false);
        btnNovo.setForeground(cinzaClaro);
        
        btnEditar.setEnabled(false);
        btnEditar.setForeground(cinzaClaro);

        btnExcluir.setEnabled(false);
        btnExcluir.setForeground(cinzaClaro);
        
        btnSalvar.setEnabled(true);
        btnSalvar.setForeground(Color.white);
        
        btnCancelar.setEnabled(true);
        btnCancelar.setForeground(Color.white);
        
        
        lblCodigo.setForeground(Color.WHITE);
        txtCodigoProduto.setEnabled(true);
        
        lblNome.setForeground(Color.WHITE);
        txtNomeProduto.setEnabled(true);
        
        lblQuantidade.setForeground(Color.WHITE);
        txtQuantidadeProduto.setEnabled(true);

        lblDataCompra.setForeground(Color.WHITE);
        jDataCompra.setEnabled(true);
        
        lblDescricao.setForeground(Color.WHITE);
        txtAreaDescricao.setEnabled(true);
        
        try {
        txtCodigoProduto.setText(jTableView.getValueAt(jTableView.getSelectedRow(), 0).toString());
        txtNomeProduto.setText(jTableView.getValueAt(jTableView.getSelectedRow(), 1).toString());
        txtQuantidadeProduto.setText(jTableView.getValueAt(jTableView.getSelectedRow(), 2).toString());
        txtAreaDescricao.setText(jTableView.getValueAt(jTableView.getSelectedRow(), 4).toString());
        
        String a = (String) jTableView.getValueAt(jTableView.getSelectedRow(), 3);
        SimpleDateFormat nova = new SimpleDateFormat("dd/MM/yyyy");
        Date dt = nova.parse(a);  
        jDataCompra.setDate(dt);
        
        } catch (Exception e) {
            System.out.println("ERRO: " + e);
        }
        
        
        jTableView.setEnabled(false);
        jTableView.clearSelection();
        txtCodigoProduto.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
               // o -1 informa se a linha esta celecionada ou nao
        if(jTableView.getSelectedRow() != -1 && jTableView.isEnabled()){
            produtoController novo = new produtoController();
            novo.deletar((int) jTableView.getValueAt(jTableView.getSelectedRow(),0));
            carregaDadosBanco();
        }        // TODO add your handling code here:
        estadoInicialView();
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    private void estadoInicialView(){
        
        btnSalvar.setEnabled(false);
        btnSalvar.setForeground(cinzaClaro);
        
        btnNovo.setEnabled(true);
        btnNovo.setForeground(Color.white);  
    
        btnSalvar.setEnabled(false);
        btnSalvar.setForeground(cinzaClaro);
     
        btnCancelar.setEnabled(false);
        btnCancelar.setForeground(cinzaClaro);
    
        btnEditar.setEnabled(false);
        btnEditar.setForeground(cinzaClaro);

        btnExcluir.setEnabled(false);
        btnExcluir.setForeground(cinzaClaro);

        txtCodigoProduto.setEnabled(false);
        lblCodigo.setForeground(cinzaClaro);

        txtNomeProduto.setEnabled(false);
        lblNome.setForeground(cinzaClaro);

        txtQuantidadeProduto.setEnabled(false);
        lblQuantidade.setForeground(cinzaClaro);

        jDataCompra.setEnabled(false);
        lblDataCompra.setForeground(cinzaClaro);

        txtAreaDescricao.setEnabled(false);
        lblDescricao.setForeground(cinzaClaro);
    
        jTableView.setEnabled(true);
    }
   
    private void carregaDadosBanco(){
        tableModel.listarProdutos();
    }
    
     private boolean naoCampoVazio(){
        boolean campo = false;
        if(txtCodigoProduto.getText().equals("") || txtNomeProduto.getText().equals("") || txtQuantidadeProduto.getText().equals("")){
            campo = false;
            JOptionPane.showMessageDialog(null, "Por gentileza preencha todos os campos!");
        }
        else{
            campo =  true;
        }
        return campo;
    }
     
     public boolean validaDate(){
        boolean checkData = false;
        
        if(jDataCompra.getDate()==null){
            JOptionPane.showMessageDialog(this, "insira uma data por gentileza!"); 
        }   
        else{
            checkData = true;
        }
        return checkData;
    }
     
      private void limpaTela(){
        txtCodigoProduto.setText("");
        txtNomeProduto.setText("");
        txtQuantidadeProduto.setText("");
        jDataCompra.setDate(null);
        txtAreaDescricao.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Novaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Novaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Novaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Novaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Novaview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private com.toedter.calendar.JDateChooser jDataCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelControleEstoque;
    private javax.swing.JPanel jPanelEmBreve;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableView;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblControleEstoque;
    private javax.swing.JLabel lblDataCompra;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTextArea txtAreaDescricao;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPesquisarProduto;
    private javax.swing.JTextField txtQuantidadeProduto;
    private javax.swing.JLabel txtminimiza;
    // End of variables declaration//GEN-END:variables


}
